[build]
command = "rm -rf __obsidian __site && mkdir __obsidian && mv * __obsidian || true && git clone https://github.com/ppeetteerrs/obsidian-zola.git __site && __site/run.sh"
publish = "public"

[build.environment]
LANDING_BUTTON = "Zapraszam"
LANDING_DESCRIPTION = ""
LANDING_PAGE = "/docs/home"  # Ensure this matches the correct file name
LANDING_TITLE = "Klątwa Strada Wiki"
PYTHON_VERSION = "3.8"
REPO_URL = "https://github.com/a-milek/Strad"
SITE_TITLE = "Strad Wiki"
SITE_TITLE_TAB = ""
SITE_URL = "https://strad-milek.netlify.app/"
TIMEZONE = "Asia/Hong_Kong"
ZOLA_VERSION = "0.15.2"
SORT_BY = "title"
GANALYTICS = ""
SLUGIFY = "y"
HOME_GRAPH = "y"
PAGE_GRAPH = "y"
LOCAL_GRAPH = "y"
GRAPH_LINK_REPLACE="y"
SIDEBAR_COLLAPSED = "y"
FOOTER = ""
ROOT_SECTION_NAME = "main"
GRAPH_OPTIONS = """
      {
      	nodes: {
      		shape: "dot",
      		color: isDark() ? "#8c8e91" : "#dee2e6",
      		font: {
      			face: "Inter",
      			color: isDark() ? "#c9cdd1" : "#616469",
      			strokeColor: isDark() ? "#c9cdd1" : "#616469",
      		},
      		scaling: {
      			label: {
      				enabled: true,
      			},
      		},
      	},
      	edges: {
      		color: { inherit: "both" },
      		width: 0.8,
      		smooth: {
      			type: "continuous",
      		},
      		hoverWidth: 4,
      	},
      	interaction: {
      		hover: true,
      	},
      	height: "100%",
      	width: "100%",
      	physics: {
      		solver: "repulsion",
      	},
      }
      """
